#!/usr/bin/env Rscript

# Build compact Extended Data Figure 3D-E candidate panels from the complete
# reviewer MRDetect platform audit generated by script 1_8C.
#
# Panel D shows the paired raw platform shift for the two MRDetect quantities
# that enter the locked models: the proportion of sites detected and the
# fraction of checked reads detected. Panel E shows why platform-matched
# normalization is required and verifies that matched 6000 and XPlus null
# distributions remain centered near zero.

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(readr)
  library(ggplot2)
  library(patchwork)
  library(scales)
})

audit_dir <- file.path("Results_MRDetect", "Reviewer_platform_shift")
component_root <- file.path(
  "Scripts_2025", "Final_Scripts", "final_manuscript_objects", "generated",
  "figure_components", "Extended_Data_Figure_3"
)
manuscript_root <- file.path(
  "Scripts_2025", "Final_Scripts", "final_manuscript_objects",
  "02_extended_data_figures", "Extended_Data_Figure_3"
)
panel_d_dir <- file.path(component_root, "panel_D")
panel_e_dir <- file.path(component_root, "panel_E")
manuscript_d_dir <- file.path(manuscript_root, "Extended_Data_Figure_3D")
manuscript_e_dir <- file.path(manuscript_root, "Extended_Data_Figure_3E")
combined_dir <- file.path(audit_dir, "Extended_Data_Figure_3D_E")
dir.create(panel_d_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(panel_e_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(manuscript_d_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(manuscript_e_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(combined_dir, recursive = TRUE, showWarnings = FALSE)

input_paths <- c(
  paired_raw = file.path(audit_dir, "Reviewer_MRDetect_paired_raw_detection_rates.csv"),
  paired_tests = file.path(audit_dir, "Reviewer_MRDetect_paired_platform_tests.csv"),
  loo = file.path(audit_dir, "Reviewer_MRDetect_leave_one_out_zscores.csv"),
  normalization = file.path(audit_dir, "Reviewer_MRDetect_matched_vs_mismatched_zscores.csv"),
  loo_comparison = file.path(audit_dir, "Reviewer_MRDetect_leave_one_out_platform_comparison.csv"),
  vcf_manifest = file.path(audit_dir, "Reviewer_MRDetect_common_VCF_timepoint_manifest.csv")
)
missing_paths <- input_paths[!file.exists(input_paths)]
if (length(missing_paths)) {
  stop(
    "Missing reviewer-audit input(s); run 1_8C first: ",
    paste(missing_paths, collapse = ", "),
    call. = FALSE
  )
}

paired_raw <- read_csv(input_paths[["paired_raw"]], show_col_types = FALSE)
paired_tests <- read_csv(input_paths[["paired_tests"]], show_col_types = FALSE)
loo <- read_csv(input_paths[["loo"]], show_col_types = FALSE)
normalization <- read_csv(input_paths[["normalization"]], show_col_types = FALSE)
loo_comparison <- read_csv(input_paths[["loo_comparison"]], show_col_types = FALSE)
vcf_manifest <- read_csv(input_paths[["vcf_manifest"]], show_col_types = FALSE)

primary_metrics <- c(
  "detection_rate_as_reads_detected_over_reads_checked",
  "sites_detection_rate"
)
metric_labels <- c(
  detection_rate_as_reads_detected_over_reads_checked = "Reads detected / reads checked",
  sites_detection_rate = "Proportion of sites detected"
)

if (sum(vcf_manifest$included_in_primary_platform_audit) != 8L ||
    any(vcf_manifest$reviewer_timepoint_group[
      vcf_manifest$included_in_primary_platform_audit
    ] != "Baseline")) {
  stop("ED3D-E requires exactly eight baseline/diagnosis VCF panels.", call. = FALSE)
}

# Panel D: paired raw platform shift -----------------------------------------
panel_d_source <- paired_raw %>%
  filter(.data$metric %in% primary_metrics) %>%
  group_by(.data$platform, .data$control_id, .data$metric) %>%
  summarise(raw_rate = median(.data$value), .groups = "drop") %>%
  mutate(
    metric_label = factor(
      unname(metric_labels[.data$metric]),
      levels = unname(metric_labels)
    ),
    platform = factor(
      as.character(.data$platform),
      levels = c("NovaSeq 6000", "NovaSeq XPlus")
    ),
    raw_rate_percent = .data$raw_rate * 100
  )

if (n_distinct(panel_d_source$control_id) != 19L ||
    nrow(panel_d_source) != 19L * 2L * 2L) {
  stop("Panel D does not contain 19 controls for both metrics and platforms.", call. = FALSE)
}

panel_d_stats <- paired_tests %>%
  filter(.data$metric %in% primary_metrics) %>%
  transmute(
    metric,
    metric_label = factor(
      unname(metric_labels[.data$metric]),
      levels = unname(metric_labels)
    ),
    ratio_of_medians,
    paired_wilcoxon_p,
    annotation = sprintf(
      "Median %.2fx\nP = %.2g",
      .data$ratio_of_medians,
      .data$paired_wilcoxon_p
    )
  )

# Panel E: matched and mismatched healthy-control z-scores -------------------
loo_e <- loo %>%
  filter(.data$metric %in% primary_metrics) %>%
  transmute(
    control_id,
    vcf_clean,
    metric,
    condition = case_when(
      .data$platform == "NovaSeq 6000" ~ "6000\nmatched",
      .data$platform == "NovaSeq XPlus" ~ "XPlus\nmatched",
      TRUE ~ NA_character_
    ),
    z_score = .data$loo_z
  )

mismatched_e <- normalization %>%
  filter(
    .data$metric %in% primary_metrics,
    .data$normalization == "XPlus using 6000 reference"
  ) %>%
  transmute(
    control_id,
    vcf_clean,
    metric,
    condition = "XPlus\nmismatched",
    z_score
  )

panel_e_source <- bind_rows(loo_e, mismatched_e) %>%
  mutate(
    metric_label = factor(
      unname(metric_labels[.data$metric]),
      levels = unname(metric_labels)
    ),
    condition = factor(
      .data$condition,
      levels = c("6000\nmatched", "XPlus\nmismatched", "XPlus\nmatched")
    )
  )

if (anyNA(panel_e_source$condition) || anyNA(panel_e_source$z_score) ||
    any(!is.finite(panel_e_source$z_score)) ||
    nrow(panel_e_source) != 19L * 8L * 2L * 3L) {
  stop("Panel E has an incomplete or non-finite matched/mismatched z-score matrix.", call. = FALSE)
}

panel_e_stats <- panel_e_source %>%
  group_by(.data$metric, .data$metric_label, .data$condition) %>%
  summarise(
    n = n(),
    median_z = median(.data$z_score),
    pct_z_gt_2 = mean(.data$z_score > 2) * 100,
    pct_abs_z_gt_2 = mean(abs(.data$z_score) > 2) * 100,
    .groups = "drop"
  )

panel_e_annotations <- panel_e_stats %>%
  filter(.data$condition %in% c("XPlus\nmismatched", "XPlus\nmatched")) %>%
  select(all_of(c("metric", "metric_label", "condition", "pct_z_gt_2"))) %>%
  pivot_wider(names_from = "condition", values_from = "pct_z_gt_2") %>%
  left_join(
    loo_comparison %>%
      filter(.data$metric %in% primary_metrics) %>%
      select(all_of(c("metric", "paired_wilcoxon_abs_z_p"))),
    by = "metric"
  ) %>%
  mutate(
    annotation = sprintf(
      "XPlus z > 2: %.0f%% vs %.0f%%\nMatched |z| vs 6000: P = %.2g",
      .data$`XPlus\nmismatched`,
      .data$`XPlus\nmatched`,
      .data$paired_wilcoxon_abs_z_p
    )
  )

# Styling --------------------------------------------------------------------
platform_colors <- c(
  "NovaSeq 6000" = "#222222",
  "NovaSeq XPlus" = "#FF3030"
)
condition_colors <- c(
  "6000\nmatched" = "#777777",
  "XPlus\nmismatched" = "#FF3030",
  "XPlus\nmatched" = "#222222"
)

base_theme <- theme_classic(base_size = 11.5, base_family = "Arial") +
  theme(
    strip.background = element_rect(fill = "grey94", colour = NA),
    strip.text = element_text(face = "plain", size = 11, margin = margin(2.5, 2, 2.5, 2)),
    plot.title = element_text(face = "bold", size = 13.5, hjust = 0.5, margin = margin(b = 5)),
    axis.title = element_text(size = 10.5),
    axis.text = element_text(size = 10.2, colour = "black"),
    axis.ticks = element_line(linewidth = 0.3),
    axis.line = element_line(linewidth = 0.35),
    panel.spacing.x = unit(7, "pt"),
    plot.margin = margin(8, 5, 4, 20)
  )

panel_d <- ggplot(
  panel_d_source,
  aes(x = .data$platform, y = .data$raw_rate_percent, group = .data$control_id)
) +
  geom_line(colour = "grey65", linewidth = 0.32, alpha = 0.65) +
  geom_point(
    aes(fill = .data$platform),
    shape = 21, size = 1.85, stroke = 0.28, colour = "white", alpha = 0.95
  ) +
  geom_text(
    data = panel_d_stats,
    aes(x = 1.5, y = Inf, label = .data$annotation),
    inherit.aes = FALSE,
    vjust = 1.2,
    size = 3.5,
    family = "Arial"
  ) +
  facet_wrap(~metric_label, scales = "free_y", nrow = 1) +
  scale_fill_manual(values = platform_colors, guide = "none") +
  scale_y_continuous(
    labels = label_number(accuracy = 0.1, suffix = "%"),
    expand = expansion(mult = c(0.06, 0.20))
  ) +
  labs(
    title = "Healthy-control cfDNA platform shift",
    x = NULL,
    y = "Raw detection rate"
  ) +
  base_theme

panel_e <- ggplot(
  panel_e_source,
  aes(x = .data$condition, y = .data$z_score, fill = .data$condition)
) +
  geom_hline(yintercept = 0, colour = "black", linewidth = 0.32) +
  geom_hline(yintercept = 2, colour = "grey45", linewidth = 0.32, linetype = 3) +
  geom_boxplot(
    width = 0.30, outlier.shape = NA,
    fill = "white", colour = "black", linewidth = 0.38
  ) +
  geom_point(
    position = position_jitter(width = 0.09, height = 0, seed = 20260730),
    shape = 21, size = 0.95, stroke = 0.17, alpha = 0.52, colour = "grey20"
  ) +
  geom_text(
    data = panel_e_annotations,
    aes(x = 1, y = Inf, label = .data$annotation),
    inherit.aes = FALSE,
    hjust = 0,
    vjust = 1.15,
    size = 3.25,
    family = "Arial"
  ) +
  facet_wrap(~metric_label, nrow = 1) +
  scale_fill_manual(values = condition_colors, guide = "none") +
  scale_y_continuous(
    trans = pseudo_log_trans(sigma = 1),
    breaks = c(-2, 0, 2, 5, 10, 20),
    expand = expansion(mult = c(0.08, 0.22))
  ) +
  labs(
    title = "Platform-matched z-score calibration",
    x = NULL,
    y = "Healthy-control z score"
  ) +
  base_theme +
  theme(axis.text.x = element_text(size = 9.8, lineheight = 0.90))

combined <- panel_d + panel_e +
  plot_layout(widths = c(0.90, 1.18)) &
  theme(plot.margin = margin(8, 5, 4, 20))

# Export ---------------------------------------------------------------------
save_plot <- function(plot, path_stub, width, height) {
  ggsave(
    paste0(path_stub, ".png"), plot,
    width = width, height = height, dpi = 600, bg = "white",
    device = ragg::agg_png
  )
  ggsave(
    paste0(path_stub, ".pdf"), plot,
    width = width, height = height, bg = "white", device = cairo_pdf
  )
  ggsave(
    paste0(path_stub, ".tiff"), plot,
    width = width, height = height, dpi = 600, bg = "white",
    device = ragg::agg_tiff, compression = "lzw"
  )
}

panel_d_stub <- file.path(panel_d_dir, "Extended_Data_Figure_3D_MRDetect_raw_platform_shift")
panel_e_stub <- file.path(panel_e_dir, "Extended_Data_Figure_3E_MRDetect_platform_matched_zscores")
combined_stub <- file.path(combined_dir, "Extended_Data_Figure_3D_E_MRDetect_platform_calibration")
manuscript_d_stub <- file.path(manuscript_d_dir, "Extended_Data_Figure_3D_MRDetect_raw_platform_shift")
manuscript_e_stub <- file.path(manuscript_e_dir, "Extended_Data_Figure_3E_MRDetect_platform_matched_zscores")
manuscript_combined_stub <- file.path(manuscript_root, "Extended_Data_Figure_3D_E_MRDetect_platform_calibration")

save_plot(panel_d, panel_d_stub, width = 6.3, height = 3.8)
save_plot(panel_e, panel_e_stub, width = 8.2, height = 3.8)
save_plot(combined, combined_stub, width = 14.5, height = 3.9)
save_plot(panel_d, manuscript_d_stub, width = 6.3, height = 3.8)
save_plot(panel_e, manuscript_e_stub, width = 8.2, height = 3.8)
save_plot(combined, manuscript_combined_stub, width = 14.5, height = 3.9)

# Placement-sized PNGs for direct insertion into the half-width manuscript
# layout. A smaller physical canvas prevents PowerPoint from shrinking the
# typography as aggressively while retaining a 600-dpi raster.
copy_ready_theme <- theme(
  plot.title = element_text(size = 14, margin = margin(b = 4)),
  strip.text = element_text(size = 10.5),
  axis.title = element_text(size = 10),
  axis.text = element_text(size = 9.5),
  panel.spacing.x = unit(5, "pt"),
  plot.margin = margin(5, 4, 3, 8)
)
copy_metric_labels <- c(
  "Reads detected / reads checked" = "Read detection",
  "Proportion of sites detected" = "Sites detected"
)
panel_d_copy <- panel_d +
  facet_wrap(
    ~metric_label, scales = "free_y", nrow = 1,
    labeller = as_labeller(copy_metric_labels)
  ) +
  scale_x_discrete(labels = c("NovaSeq 6000" = "6000", "NovaSeq XPlus" = "XPlus")) +
  labs(title = "Healthy-control platform shift") +
  copy_ready_theme
panel_e_copy <- panel_e +
  facet_wrap(
    ~metric_label, nrow = 1,
    labeller = as_labeller(copy_metric_labels)
  ) +
  copy_ready_theme
ggsave(
  file.path(manuscript_d_dir, "ED3D.png"),
  panel_d_copy,
  width = 5.1, height = 2.5, dpi = 600, bg = "white",
  device = ragg::agg_png
)
ggsave(
  file.path(manuscript_e_dir, "ED3E.png"),
  panel_e_copy,
  width = 6.1, height = 2.5, dpi = 600, bg = "white",
  device = ragg::agg_png
)

# Nature production raster at the final 180-mm Extended Data page width. This
# rescales the already-verified 14.5-inch composition, preserving its effective
# typography while writing exactly 300 pixels per inch at the target width.
combined_png_image <- png::readPNG(paste0(combined_stub, ".png"))
nature_width_mm <- 180
nature_height_mm <- nature_width_mm * dim(combined_png_image)[1] / dim(combined_png_image)[2]
ragg::agg_tiff(
  paste0(combined_stub, "_Nature_180mm_300dpi.tiff"),
  width = nature_width_mm,
  height = nature_height_mm,
  units = "mm",
  res = 300,
  compression = "lzw",
  bg = "white"
)
grid::grid.newpage()
grid::grid.raster(combined_png_image, interpolate = TRUE)
grDevices::dev.off()
if (!file.copy(
  paste0(combined_stub, "_Nature_180mm_300dpi.tiff"),
  paste0(manuscript_combined_stub, "_Nature_180mm_300dpi.tiff"),
  overwrite = TRUE
)) {
  stop("Failed to copy the Nature-resolution TIFF to the manuscript-object tree.", call. = FALSE)
}
write_csv(
  panel_d_source,
  file.path(panel_d_dir, "Extended_Data_Figure_3D_source_data.csv")
)
write_csv(
  panel_d_stats,
  file.path(panel_d_dir, "Extended_Data_Figure_3D_statistics.csv")
)
write_csv(
  panel_e_source,
  file.path(panel_e_dir, "Extended_Data_Figure_3E_source_data.csv")
)
write_csv(
  panel_e_stats,
  file.path(panel_e_dir, "Extended_Data_Figure_3E_statistics.csv")
)
write_csv(
  panel_d_source,
  file.path(manuscript_d_dir, "Extended_Data_Figure_3D_source_data.csv")
)
write_csv(
  panel_d_stats,
  file.path(manuscript_d_dir, "Extended_Data_Figure_3D_statistics.csv")
)
write_csv(
  panel_e_source,
  file.path(manuscript_e_dir, "Extended_Data_Figure_3E_source_data.csv")
)
write_csv(
  panel_e_stats,
  file.path(manuscript_e_dir, "Extended_Data_Figure_3E_statistics.csv")
)
# Keep the panel assignment next to the manuscript components so that
# subsequent assembly and source-data exports retain the D-E lettering.
panel_manifest <- tibble::tribble(
  ~figure, ~panel, ~status, ~description, ~generator_script, ~primary_component_png, ~source_data, ~notes,
  "Extended Data Figure 3", "A", "existing", "Baseline BM-informed longitudinal tracking", "2_4_Longitudinal_features_analysis.R", "panel_A/ED3A_longitudinal.png", "panel_A/Extended_Data_Figure_3A_BM_raw_longitudinal_features_source_data.csv", "Existing manuscript panel.",
  "Extended Data Figure 3", "B", "existing", "Baseline cfDNA-informed longitudinal tracking", "2_4_Longitudinal_features_analysis.R", "panel_B/ED3B_longitudinal.png", "panel_B/Extended_Data_Figure_3B_blood_raw_longitudinal_features_source_data.csv", "Existing manuscript panel.",
  "Extended Data Figure 3", "C", "existing", "Fragmentomic tumour-agnostic longitudinal tracking", "2_4_Longitudinal_features_analysis.R", "panel_C/ED3C_longitudinal.png", "panel_C/Extended_Data_Figure_3C_fragmentomics_additional_longitudinal_features_source_data.csv", "Existing manuscript panel.",
  "Extended Data Figure 3", "D", "generated", "Paired raw MRDetect healthy-control platform shift", "1_8D_Build_ED3DE_MRDetect_Platform_Calibration.R", "panel_D/Extended_Data_Figure_3D_MRDetect_raw_platform_shift.png", "panel_D/Extended_Data_Figure_3D_source_data.csv", "Nineteen paired healthy-control identities and eight baseline/diagnosis VCF panels.",
  "Extended Data Figure 3", "E", "generated", "MRDetect platform-matched z-score calibration", "1_8D_Build_ED3DE_MRDetect_Platform_Calibration.R", "panel_E/Extended_Data_Figure_3E_MRDetect_platform_matched_zscores.png", "panel_E/Extended_Data_Figure_3E_source_data.csv", "Boxplots with jittered observations; no violin layer."
)
write_csv(
  panel_manifest,
  file.path(component_root, "Extended_Data_Figure_3_panel_manifest.csv"),
  na = ""
)
manuscript_manifest <- panel_manifest %>%
  mutate(
    primary_component_png = case_when(
      .data$panel == "A" ~ "Extended_Data_Figure_3A/ED3A_longitudinal.png",
      .data$panel == "B" ~ "Extended_Data_Figure_3B/ED3B_longitudinal.png",
      .data$panel == "C" ~ "Extended_Data_Figure_3C/ED3C_longitudinal.png",
      .data$panel == "D" ~ "Extended_Data_Figure_3D/Extended_Data_Figure_3D_MRDetect_raw_platform_shift.png",
      .data$panel == "E" ~ "Extended_Data_Figure_3E/Extended_Data_Figure_3E_MRDetect_platform_matched_zscores.png",
      TRUE ~ .data$primary_component_png
    ),
    source_data = case_when(
      .data$panel == "A" ~ "../../generated/figure_components/Extended_Data_Figure_3/panel_A/Extended_Data_Figure_3A_BM_raw_longitudinal_features_source_data.csv",
      .data$panel == "B" ~ "../../generated/figure_components/Extended_Data_Figure_3/panel_B/Extended_Data_Figure_3B_blood_raw_longitudinal_features_source_data.csv",
      .data$panel == "C" ~ "../../generated/figure_components/Extended_Data_Figure_3/panel_C/Extended_Data_Figure_3C_fragmentomics_additional_longitudinal_features_source_data.csv",
      .data$panel == "D" ~ "Extended_Data_Figure_3D/Extended_Data_Figure_3D_source_data.csv",
      .data$panel == "E" ~ "Extended_Data_Figure_3E/Extended_Data_Figure_3E_source_data.csv",
      TRUE ~ .data$source_data
    )
  )
write_csv(
  manuscript_manifest,
  file.path(manuscript_root, "Extended_Data_Figure_3_panel_manifest.csv"),
  na = ""
)

caption_lines <- c(
  "Extended Data Fig. 3d,e | Cross-platform calibration of MRDetect healthy-control cfDNA measurements.",
  "d, Paired raw healthy-control detection rates on NovaSeq 6000 and NovaSeq XPlus for the two MRDetect quantities used by the locked models. Each point represents one of 19 healthy-control identities and lines connect the same identity across platforms; values are identity-level medians across eight baseline/diagnosis VCF panels. P values are from two-sided paired Wilcoxon tests.",
  "e, Healthy-control z-score distributions for the same two metrics. NovaSeq 6000 and platform-matched XPlus values were calculated using leave-one-control-out references from the corresponding platform; the mismatched condition applies the NovaSeq 6000 reference to XPlus controls. Jittered points represent 152 control-VCF observations per metric (19 controls x 8 VCF panels); boxes show medians and interquartile ranges, with whiskers extending to 1.5 times the interquartile range. Dotted lines indicate z = 2. P values compare paired absolute leave-one-out z scores between the platform-matched NovaSeq 6000 and XPlus conditions."
)
writeLines(
  caption_lines,
  file.path(combined_dir, "Extended_Data_Figure_3D_E_caption.txt")
)
writeLines(
  caption_lines,
  file.path(manuscript_root, "Extended_Data_Figure_3D_E_caption.txt")
)
writeLines(
  "Extended Data Figure 3: Additional longitudinal MRD dynamics and cross-platform calibration of cfDNA measurements",
  file.path(combined_dir, "Extended_Data_Figure_3_recommended_revised_title.txt")
)
writeLines(
  "Extended Data Figure 3: Additional longitudinal MRD dynamics and cross-platform calibration of cfDNA measurements",
  file.path(manuscript_root, "Extended_Data_Figure_3_recommended_revised_title.txt")
)

message("Extended Data Figure 3D-E candidate written: ", paste0(combined_stub, ".png"))
message("Panel D component: ", paste0(panel_d_stub, ".png"))
message("Panel E component: ", paste0(panel_e_stub, ".png"))
message("Manuscript-facing ED3D-E directory: ", manuscript_root)
message(
  "Panel manifest: ",
  file.path(component_root, "Extended_Data_Figure_3_panel_manifest.csv")
)
