#!/usr/bin/env Rscript

# Purpose -----------------------------------------------------------------
# Build an alternate dilution-series correlation panel from the Spring 2026
# PWGVAL/M4CHIP release. Unlike the legacy Figure 3C lollipop, this version
# preserves the patient and technical-replicate structure.
#
# Statistical summary -----------------------------------------------------
# 1. Calculate Spearman rho separately for every feature, patient, and
#    technical replicate (six series: three patients x two replicates).
# 2. Average the two replicate-level rho values within each patient.
# 3. Take an equal-patient arithmetic mean of the three patient means.
#
# This is a descriptive reproducibility summary, not an inferential
# meta-analysis. The range shown in the figure is the range of the three
# patient means; it is not a confidence interval. A direct arithmetic mean is
# used because Fisher's z transformation is derived for Pearson correlations
# and several short dilution series can yield rho = +/-1.
#
# Inputs are the de-identified, point-level source-data tables generated by:
#   3_1_part2_Apply_cfWGS_thresholds_to_dilution_series.R
#
# Outputs:
#   Final Tables and Figures/
#     Fig3C_alt_dilution_feature_rho_by_patient_replicate.png
#     Fig3C_alt_dilution_feature_rho_by_patient_replicate.pdf
#     Fig3C_alt_dilution_feature_rho_patient_means_simple.png
#     Fig3C_alt_dilution_feature_rho_patient_means_simple.pdf
#   Output_tables_2025/Source_Data_Extended_Data/
#     SourceData_Fig3C_alt_dilution_feature_rho_by_patient_replicate.csv

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(readr)
})

.manuscript_helper <- file.path(
  "Scripts_2025", "Final_Scripts", "manuscript_output_helpers.R"
)
if (!file.exists(.manuscript_helper)) {
  .manuscript_helper <- "manuscript_output_helpers.R"
}
source(.manuscript_helper)
rm(.manuscript_helper)

set.seed(20260714)

project_root <- normalizePath(".", mustWork = TRUE)
input_dir <- file.path(
  project_root,
  "Output_tables_2025",
  "Source_Data_Extended_Data"
)
figure_dir <- file.path(project_root, "Final Tables and Figures")

input_paths <- c(
  bm = file.path(
    input_dir,
    "SourceData_Fig4G_BM_patient_series_points_zero_final_tf.csv"
  ),
  blood = file.path(
    input_dir,
    "SourceData_Fig5G_Blood_patient_series_points_zero_final_tf.csv"
  ),
  fragmentomics = file.path(
    input_dir,
    "SourceData_Fragmentomics_main_models_patient_series_zero_final_tf.csv"
  )
)

missing_inputs <- input_paths[!file.exists(input_paths)]
if (length(missing_inputs) > 0L) {
  stop(
    "Missing required dilution-series source-data file(s): ",
    paste(missing_inputs, collapse = ", "),
    call. = FALSE
  )
}
if (!dir.exists(figure_dir)) {
  dir.create(figure_dir, recursive = TRUE)
}

feature_labels <- c(
  detect_rate_BM = "BM-derived cumulative VAF (cVAF)",
  z_score_detection_rate_BM = "BM-derived cVAF z-score",
  zscore_BM = "BM-derived prop. mutant sites detected z-score",
  detect_rate_blood = "Blood-derived cumulative VAF (cVAF)",
  z_score_detection_rate_blood = "Blood-derived cVAF z-score",
  zscore_blood = "Blood-derived prop. mutant sites detected z-score",
  Mean.Coverage = "MM regulatory coverage",
  Proportion.Short = "Short-fragment proportion",
  FS = "Fragment-size score",
  WGS_Tumor_Fraction_Blood_plasma_cfDNA = "CNA tumour fraction (ichorCNA)",
  BM_zscore_only_detection_rate_prob = "BM-derived cVAF model probability",
  Blood_plus_fragment_prob = "Blood-derived combined model probability",
  Blood_zscore_only_sites_prob = "Blood-derived prop. sites model probability"
)

required_columns <- c(
  "Patient", "replicate_id", "series_label", "feature", "value",
  "LOD_zero_final"
)

read_source <- function(path, source_group) {
  dat <- readr::read_csv(path, show_col_types = FALSE)
  missing_columns <- setdiff(required_columns, names(dat))
  if (length(missing_columns) > 0L) {
    stop(
      basename(path), " is missing required column(s): ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }
  dat %>% mutate(source_group = source_group)
}

combined_points <- bind_rows(
  read_source(input_paths[["bm"]], "BM-informed"),
  read_source(input_paths[["blood"]], "Blood-informed"),
  read_source(input_paths[["fragmentomics"]], "Fragmentomics")
) %>%
  filter(.data$feature %in% names(feature_labels)) %>%
  distinct(
    .data$Patient,
    .data$replicate_id,
    .data$feature,
    .data$LOD_zero_final,
    .keep_all = TRUE
  )

all_points <- combined_points %>%
  filter(.data$series_label == "PWGVAL M4CHIP")

if (nrow(all_points) == 0L) {
  stop("No Spring 2026 PWGVAL/M4CHIP dilution points were found.", call. = FALSE)
}
if (anyNA(all_points[, c("Patient", "replicate_id", "feature")])) {
  stop("Patient, replicate, and feature identifiers must not be missing.", call. = FALSE)
}

patients <- sort(unique(all_points$Patient))
replicates <- sort(unique(all_points$replicate_id))
if (length(patients) != 3L) {
  stop(
    "Expected exactly 3 PWGVAL/M4CHIP patients; found ", length(patients),
    ": ", paste(patients, collapse = ", "),
    call. = FALSE
  )
}
if (!identical(replicates, c("rep01", "rep02"))) {
  stop(
    "Expected technical replicates rep01 and rep02; found: ",
    paste(replicates, collapse = ", "),
    call. = FALSE
  )
}

series_qc <- all_points %>%
  group_by(.data$feature, .data$Patient, .data$replicate_id) %>%
  summarise(
    n_complete = sum(complete.cases(.data$LOD_zero_final, .data$value)),
    n_lod = n_distinct(.data$LOD_zero_final[!is.na(.data$LOD_zero_final)]),
    n_value = n_distinct(.data$value[!is.na(.data$value)]),
    .groups = "drop"
  )

expected_series <- tidyr::expand_grid(
  feature = names(feature_labels),
  Patient = patients,
  replicate_id = replicates
)
missing_series <- anti_join(
  expected_series,
  series_qc,
  by = c("feature", "Patient", "replicate_id")
)
if (nrow(missing_series) > 0L) {
  stop(
    "At least one expected feature/patient/replicate series is missing. ",
    "First missing series: ",
    paste(unlist(missing_series[1, ]), collapse = " / "),
    call. = FALSE
  )
}
if (any(series_qc$n_complete < 3L | series_qc$n_lod < 3L | series_qc$n_value < 2L)) {
  bad <- series_qc %>%
    filter(.data$n_complete < 3L | .data$n_lod < 3L | .data$n_value < 2L)
  stop(
    "Insufficient complete or variable observations for Spearman correlation. ",
    "First failing series: ", paste(unlist(bad[1, ]), collapse = " / "),
    call. = FALSE
  )
}

replicate_rho <- all_points %>%
  group_by(.data$feature, .data$Patient, .data$replicate_id) %>%
  summarise(
    rho = suppressWarnings(cor(
      .data$value,
      .data$LOD_zero_final,
      method = "spearman",
      use = "complete.obs"
    )),
    n_complete = sum(complete.cases(.data$LOD_zero_final, .data$value)),
    n_lod = n_distinct(.data$LOD_zero_final[complete.cases(
      .data$LOD_zero_final,
      .data$value
    )]),
    .groups = "drop"
  )

if (anyNA(replicate_rho$rho) || any(abs(replicate_rho$rho) > 1)) {
  stop("Invalid replicate-level Spearman correlation(s) were produced.", call. = FALSE)
}

patient_mean_rho <- replicate_rho %>%
  group_by(.data$feature, .data$Patient) %>%
  summarise(
    rho = mean(.data$rho),
    n_replicates = n(),
    .groups = "drop"
  )

if (any(patient_mean_rho$n_replicates != 2L)) {
  stop("Each patient must contribute exactly two replicate correlations.", call. = FALSE)
}

overall_rho <- patient_mean_rho %>%
  group_by(.data$feature) %>%
  summarise(
    patient_mean_min = min(.data$rho),
    patient_mean_max = max(.data$rho),
    rho = mean(.data$rho),
    n_patients = n(),
    .groups = "drop"
  )

if (any(overall_rho$n_patients != 3L)) {
  stop("Each feature must contribute exactly three patient means.", call. = FALSE)
}

source_data <- bind_rows(
  replicate_rho %>%
    transmute(
      feature,
      plot_label = unname(feature_labels[.data$feature]),
      summary_level = "patient_replicate",
      Patient,
      replicate_id,
      rho,
      n_complete,
      n_lod,
      n_replicates = NA_integer_,
      n_patients = NA_integer_,
      patient_mean_min = NA_real_,
      patient_mean_max = NA_real_
    ),
  patient_mean_rho %>%
    transmute(
      feature,
      plot_label = unname(feature_labels[.data$feature]),
      summary_level = "patient_mean",
      Patient,
      replicate_id = NA_character_,
      rho,
      n_complete = NA_integer_,
      n_lod = NA_integer_,
      n_replicates,
      n_patients = NA_integer_,
      patient_mean_min = NA_real_,
      patient_mean_max = NA_real_
    ),
  overall_rho %>%
    transmute(
      feature,
      plot_label = unname(feature_labels[.data$feature]),
      summary_level = "equal_patient_mean",
      Patient = NA_character_,
      replicate_id = NA_character_,
      rho,
      n_complete = NA_integer_,
      n_lod = NA_integer_,
      n_replicates = NA_integer_,
      n_patients,
      patient_mean_min,
      patient_mean_max
    )
) %>%
  arrange(.data$feature, factor(
    .data$summary_level,
    levels = c("patient_replicate", "patient_mean", "equal_patient_mean")
  ), .data$Patient, .data$replicate_id)

source_path <- file.path(
  input_dir,
  "SourceData_Fig3C_alt_dilution_feature_rho_by_patient_replicate.csv"
)
write_csv(source_data, source_path, na = "")

feature_order <- overall_rho %>%
  arrange(.data$rho) %>%
  pull(.data$feature)

replicate_plot <- replicate_rho %>%
  mutate(
    feature = factor(.data$feature, levels = feature_order),
    replicate_id = factor(
      .data$replicate_id,
      levels = c("rep01", "rep02"),
      labels = c("Replicate 1", "Replicate 2")
    )
  )

overall_plot <- overall_rho %>%
  mutate(feature = factor(.data$feature, levels = feature_order))

patient_colors <- setNames(
  c("#0072B2", "#D55E00", "#009E73"),
  patients
)

p <- ggplot() +
  geom_vline(xintercept = 0, colour = "grey75", linetype = "dashed") +
  geom_segment(
    data = overall_plot,
    aes(
      x = .data$patient_mean_min,
      xend = .data$patient_mean_max,
      y = .data$feature,
      yend = .data$feature
    ),
    colour = "grey45",
    linewidth = 0.65
  ) +
  geom_point(
    data = replicate_plot,
    aes(
      x = .data$rho,
      y = .data$feature,
      colour = .data$Patient,
      shape = .data$replicate_id
    ),
    size = 2.25,
    alpha = 0.88,
    stroke = 0.75,
    position = position_dodge(width = 0.42)
  ) +
  geom_point(
    data = overall_plot,
    aes(x = .data$rho, y = .data$feature),
    shape = 23,
    size = 3.5,
    stroke = 0.75,
    fill = "black",
    colour = "white"
  ) +
  scale_colour_manual(values = patient_colors, name = "Patient") +
  scale_shape_manual(
    values = c("Replicate 1" = 16, "Replicate 2" = 1),
    name = NULL
  ) +
  scale_x_continuous(
    limits = c(-1.02, 1.02),
    breaks = seq(-1, 1, by = 0.5),
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  scale_y_discrete(labels = feature_labels) +
  labs(
    title = "Feature Correlation Across Three Dilution-Series Patients",
    subtitle = paste(
      "Points: patient-specific technical replicates;",
      "black diamond: equal-patient mean; line: range of patient means"
    ),
    x = expression(rho ~ "(Spearman)"),
    y = NULL
  ) +
  guides(
    colour = guide_legend(order = 1, override.aes = list(shape = 16)),
    shape = guide_legend(order = 2)
  ) +
  theme_minimal(base_size = 9) +
  theme(
    plot.title.position = "plot",
    plot.title = element_text(face = "bold", size = 11),
    plot.subtitle = element_text(size = 8.2, colour = "grey25"),
    axis.text.y = element_text(size = 7.8, colour = "black"),
    axis.text.x = element_text(size = 8, colour = "black"),
    axis.title.x = element_text(size = 8.5, margin = margin(t = 5)),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.text = element_text(size = 7.5),
    legend.title = element_text(size = 7.5, face = "bold"),
    plot.margin = margin(7, 8, 6, 7)
  )

png_path <- file.path(
  figure_dir,
  "Fig3C_alt_dilution_feature_rho_by_patient_replicate.png"
)
pdf_path <- file.path(
  figure_dir,
  "Fig3C_alt_dilution_feature_rho_by_patient_replicate.pdf"
)

ggsave(png_path, p, width = 7.1, height = 5.7, dpi = 600, bg = "white")
ggsave(pdf_path, p, width = 7.1, height = 5.7, device = cairo_pdf, bg = "white")

# Simplified manuscript-facing version ------------------------------------
# Technical-replicate rho values remain available in the source table and
# detailed figure above. Here each coloured point is the within-patient mean
# of two technical-replicate rho values, and the black diamond is the
# equal-patient mean. This retains the three-patient structure with four marks
# per feature and restores the visual simplicity of the legacy lollipop.
simple_labels <- c(
  detect_rate_BM = "BM-derived cVAF",
  z_score_detection_rate_BM = "BM-derived cVAF z-score",
  zscore_BM = "BM-derived mutant-sites z-score",
  detect_rate_blood = "Blood-derived cVAF",
  z_score_detection_rate_blood = "Blood-derived cVAF z-score",
  zscore_blood = "Blood-derived mutant-sites z-score",
  Mean.Coverage = "MM regulatory coverage",
  Proportion.Short = "Short-fragment proportion",
  FS = "Fragment-size score",
  WGS_Tumor_Fraction_Blood_plasma_cfDNA = "CNA tumour fraction (ichorCNA)",
  BM_zscore_only_detection_rate_prob = "BM-derived cVAF model",
  Blood_plus_fragment_prob = "Blood-derived combined model",
  Blood_zscore_only_sites_prob = "Blood-derived mutant-sites model"
)

patient_mean_plot <- patient_mean_rho %>%
  mutate(feature = factor(.data$feature, levels = feature_order))

p_simple <- ggplot() +
  geom_vline(xintercept = 0, colour = "grey78", linetype = "dashed") +
  geom_segment(
    data = overall_plot,
    aes(x = 0, xend = .data$rho, y = .data$feature, yend = .data$feature),
    colour = "grey78",
    linewidth = 0.45
  ) +
  geom_point(
    data = patient_mean_plot,
    aes(x = .data$rho, y = .data$feature, colour = .data$Patient),
    size = 2.35,
    alpha = 0.9,
    position = position_dodge(width = 0.38)
  ) +
  geom_point(
    data = overall_plot,
    aes(x = .data$rho, y = .data$feature),
    shape = 23,
    size = 3.35,
    stroke = 0.7,
    fill = "black",
    colour = "white"
  ) +
  scale_colour_manual(values = patient_colors, name = "Patient mean") +
  scale_x_continuous(
    limits = c(-1.02, 1.02),
    breaks = seq(-1, 1, by = 0.5),
    expand = expansion(mult = c(0.01, 0.01))
  ) +
  scale_y_discrete(labels = simple_labels) +
  labs(
    title = "Feature Correlation Across Patients",
    subtitle = "Dots: mean of 2 technical replicates; black diamond: mean of 3 patients",
    x = expression(rho ~ "(Spearman)"),
    y = NULL
  ) +
  theme_minimal(base_size = 8.5) +
  theme(
    plot.title.position = "plot",
    plot.title = element_text(face = "bold", size = 10.5),
    plot.subtitle = element_text(size = 7.5, colour = "grey30"),
    axis.text.y = element_text(size = 7.4, colour = "black"),
    axis.text.x = element_text(size = 7.5, colour = "black"),
    axis.title.x = element_text(size = 8, margin = margin(t = 4)),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "bottom",
    legend.title = element_text(size = 7.2, face = "bold"),
    legend.text = element_text(size = 7.2),
    plot.margin = margin(6, 7, 5, 6)
  )

simple_png_path <- file.path(
  figure_dir,
  "Fig3C_alt_dilution_feature_rho_patient_means_simple.png"
)
simple_pdf_path <- file.path(
  figure_dir,
  "Fig3C_alt_dilution_feature_rho_patient_means_simple.pdf"
)

ggsave(
  simple_png_path,
  p_simple,
  width = 5.7,
  height = 4.8,
  dpi = 600,
  bg = "white"
)
ggsave(
  simple_pdf_path,
  p_simple,
  width = 5.7,
  height = 4.8,
  device = cairo_pdf,
  bg = "white"
)

message("Saved figure: ", png_path)
message("Saved figure: ", pdf_path)
message("Saved simplified figure: ", simple_png_path)
message("Saved simplified figure: ", simple_pdf_path)
message("Saved source data: ", source_path)
message(
  "QC: ", length(patients), " patients; ", length(replicates),
  " replicates per patient; ", length(feature_labels), " features."
)
