# Packages required across the analysis scripts.
packages <- c(
  "BoutrosLab.plotting.general",
  "ChromHeatMap",
  "ComplexHeatmap",
  "DescTools",
  "GGally",
  "GeneCycle",
  "GenomicRanges",
  "Hmisc",
  "Matrix",
  "PRROC",
  "RColorBrewer",
  "VennDiagram",
  "broom",
  "caret",
  "circlize",
  "conflicted",
  "data.table",
  "doParallel",
  "dplyr",
  "exact2x2",
  "flextable",
  "forcats",
  "fuzzyjoin",
  "ggbreak",
  "ggplot2",
  "ggpubr",
  "ggridges",
  "glmnet",
  "glue",
  "gridExtra",
  "gt",
  "gtsummary",
  "janitor",
  "lubridate",
  "maftools",
  "officer",
  "openxlsx",
  "pROC",
  "patchwork",
  "pbapply",
  "purrr",
  "readr",
  "readxl",
  "reshape2",
  "rlang",
  "rmda",
  "rstatix",
  "scales",
  "stringdist",
  "stringr",
  "survival",
  "survminer",
  "tableone",
  "tibble",
  "tidyr",
  "tidyverse",
  "timeROC",
  "viridis",
  "viridisLite",
  "writexl",
  "yardstick"
)

# Central configuration of directory locations.
# Update these variables to match your local environment.

clinical_data_dir <- "Clinical data"
wgs_results_dir   <- "M4_CMRG_Data"
output_tables_dir <- "Output_tables_2025"
